# Generated by Django 5.0.6 on 2024-07-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedEmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_student', models.CharField(max_length=255)),
                ('jsn_iin', models.CharField(max_length=255)),
                ('payment_amount', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
    ]
