version: '3'

services:
  django:
    build: .
    command: gunicorn stud_test.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True  # Set to False in production
      - DJANGO_SETTINGS_MODULE=stud_test.settings

