version: '3'

services:
  app:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 stud_test.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
      - react

volumes:
  static_volume:
  media_volume:
