version: '3'

services:
  app:
    build: /home/ubuntu/web/eoa_test
    command: gunicorn --bind 0.0.0.0:8000 stud_test.wsgi:application
    volumes:
      - /home/ubuntu/web/eoa_test:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000

  react:
    build:
      context: /home/ubuntu/web/eoa_test/frontend
      dockerfile: Dockerfile
    volumes:
      - /home/ubuntu/web/eoa_test/frontend:/app
    expose:
      - 80
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/web/eoa_test/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - react

volumes:
  static_volume:
  media_volume:
