# Generated by Django 5.0.6 on 2024-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_link',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
