# Generated by Django 5.0.6 on 2024-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_referral_bonus_user_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
